name: cv-builder

services:
  postgres:
    image: postgres:latest
    ports:
      - '6502:5432'
    volumes:
      - ./server/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./server/.env

volumes:
  postgresDB:
